defaults:
  - analyzer: default.yaml
  - analyzer/reader: default.yaml
  - analyzer/detector: retinaface.yaml
  - analyzer/unifier: img_380.yaml
  - analyzer/predictor/embed: r50_vggface_1m.yaml
  - analyzer/predictor/verify: r100_magface_unpg.yaml
  - analyzer/predictor/fer: efficientnet_b0_7.yaml
  - analyzer/predictor/deepfake: efficientnet_b7.yaml
  - analyzer/predictor/align: synergy_mobilenet_v2.yaml
  - analyzer/utilizer/align: lmk3d_mesh_pose.yaml
  - analyzer/utilizer/draw_boxes: torchvision_boxes.yaml
  - analyzer/utilizer/draw_landmarks: torchvision_keypoints.yaml
  - analyzer/utilizer/save: image_saver.yaml
  - analyzer/logger: json_format.yaml
  - _self_

main:
    sleep: 3

debug: true

path_image: /opt/facetorch/data/input/test2.jpg # str
batch_size: 8 # int
fix_img_size: True # bool
return_img_data: False # bool
include_tensors: False # bool
path_output: /opt/facetorch/tests/data/output/test2.jpg # Optional[str]